// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SlnErp102.Data;

#nullable disable

namespace SlnErp102.Data.Migrations
{
    [DbContext(typeof(SlnDbContext))]
    partial class SlnDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SlnErp102.Core.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("tblCities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Istanbul",
                            Region = "Marmara"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ankara",
                            Region = "Ic Anadolu"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Izmir",
                            Region = "Ege"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Antalya",
                            Region = "Akdeniz"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Diyarbakir",
                            Region = "Guney Dogu Anadolu"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Samsun",
                            Region = "Karadeniz"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Kars",
                            Region = "Dogu Anadolu"
                        });
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("tblDepartments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Satin Alma",
                            Type = "H"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Finans",
                            Type = "H"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ameliyathane",
                            Type = "H"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Rektorluk",
                            Type = "H"
                        },
                        new
                        {
                            Id = 5,
                            Name = "IK",
                            Type = "H"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Hasta Haklari",
                            Type = "H"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Finans",
                            Type = "C"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Satin Alma",
                            Type = "C"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Depo",
                            Type = "C"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Sahip",
                            Type = "C"
                        });
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Companies.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CompanyTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("date");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("date");

                    b.Property<string>("ModifiedUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyTypeId");

                    b.ToTable("tblCompanies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyTypeId = 1,
                            CreatedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(8082),
                            ModifiedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(8083),
                            ModifiedUser = "system",
                            Name = "Ortek"
                        },
                        new
                        {
                            Id = 2,
                            CompanyTypeId = 2,
                            CreatedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(8085),
                            ModifiedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(8086),
                            ModifiedUser = "system",
                            Name = "Syntex"
                        },
                        new
                        {
                            Id = 3,
                            CompanyTypeId = 3,
                            CreatedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(8088),
                            ModifiedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(8088),
                            ModifiedUser = "system",
                            Name = "Kayacan"
                        });
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Companies.CompanyBranch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("date");

                    b.Property<string>("InvoiceTitle")
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("date");

                    b.Property<string>("ModifiedUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CompanyId");

                    b.ToTable("tblCompanyBranches", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Esenyurt",
                            CityId = 1,
                            CompanyId = 1,
                            CreatedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(7869),
                            InvoiceTitle = "Ortek Ltd.Sti",
                            ModifiedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(7869),
                            ModifiedUser = "system",
                            Name = "Merkez"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Izmir",
                            CityId = 2,
                            CompanyId = 1,
                            CreatedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(7871),
                            InvoiceTitle = "Ortek Ltd.Sti",
                            ModifiedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(7872),
                            ModifiedUser = "system",
                            Name = "Izmir Sube"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Ankara",
                            CityId = 3,
                            CompanyId = 1,
                            CreatedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(7873),
                            InvoiceTitle = "Ortek Ltd.Sti",
                            ModifiedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(7874),
                            ModifiedUser = "system",
                            Name = "Ankara Sube"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Esenyurt",
                            CityId = 1,
                            CompanyId = 2,
                            CreatedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(7875),
                            InvoiceTitle = "Ortek Ltd.Sti",
                            ModifiedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(7876),
                            ModifiedUser = "system",
                            Name = "Merkez"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Izmir",
                            CityId = 2,
                            CompanyId = 2,
                            CreatedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(7877),
                            InvoiceTitle = "Ortek Ltd.Sti",
                            ModifiedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(7878),
                            ModifiedUser = "system",
                            Name = "Izmir Sube"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Ankara",
                            CityId = 3,
                            CompanyId = 2,
                            CreatedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(7879),
                            InvoiceTitle = "Ortek Ltd.Sti",
                            ModifiedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(7879),
                            ModifiedUser = "system",
                            Name = "Ankara Sube"
                        });
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Companies.CompanyDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Fax")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gsm")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Officer")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("tblCompanyDetails", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            DepartmentId = 7,
                            Email = "111@gmail.com",
                            Fax = "111",
                            Gsm = "111",
                            Officer = "Sinan",
                            Phone = "111"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            DepartmentId = 8,
                            Email = "222@gmail.com",
                            Fax = "222",
                            Gsm = "222",
                            Officer = "Sukran",
                            Phone = "222"
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 1,
                            DepartmentId = 9,
                            Email = "333@gmail.com",
                            Fax = "333",
                            Gsm = "333",
                            Officer = "Turgay",
                            Phone = "333"
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = 1,
                            DepartmentId = 10,
                            Email = "444@gmail.com",
                            Fax = "444",
                            Gsm = "444",
                            Officer = "Tahir",
                            Phone = "444"
                        });
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Companies.CompanyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("tblCompanyTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Musteri"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tedarikci"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ana Satici"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Distributor"
                        });
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Doctors.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("date");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("ClinicAddress")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("date");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("date");

                    b.Property<string>("ModifiedUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Title")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("tblDoctors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDay = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(8197),
                            CityId = 1,
                            ClinicAddress = "Fulya/Besiktas",
                            CreatedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(8198),
                            ModifiedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(8198),
                            ModifiedUser = "system",
                            Name = "Omer Taser",
                            Title = 0
                        },
                        new
                        {
                            Id = 2,
                            BirthDay = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(8200),
                            CityId = 1,
                            ClinicAddress = "Tesvikiye/Sisli",
                            CreatedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(8201),
                            ModifiedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(8202),
                            ModifiedUser = "system",
                            Name = "Mehmet Demirhan",
                            Title = 0
                        },
                        new
                        {
                            Id = 3,
                            BirthDay = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(8203),
                            CityId = 1,
                            ClinicAddress = "Abide-i Hürriyet Cd No:166, 34381 Şişli/İstanbul",
                            CreatedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(8203),
                            ModifiedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(8204),
                            ModifiedUser = "system",
                            Name = "Azmi Hamzaoglu",
                            Title = 0
                        });
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Doctors.DoctorDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Fax")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gsm")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("HospitalId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("HospitalId");

                    b.ToTable("tblDoctorDetails", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DoctorId = 1,
                            Email = "taser@gmail.com",
                            Fax = "111",
                            Gsm = "111",
                            HospitalId = 1,
                            Phone = "111"
                        },
                        new
                        {
                            Id = 2,
                            DoctorId = 2,
                            Email = "demirhan@gmail.com",
                            Fax = "222",
                            Gsm = "222",
                            HospitalId = 3,
                            Phone = "222"
                        },
                        new
                        {
                            Id = 3,
                            DoctorId = 3,
                            Email = "hamzaoglu@gmail.com",
                            Fax = "333",
                            Gsm = "333",
                            HospitalId = 2,
                            Phone = "333"
                        },
                        new
                        {
                            Id = 4,
                            DoctorId = 3,
                            Email = "",
                            Fax = "",
                            Gsm = "",
                            HospitalId = 6,
                            Phone = "444"
                        });
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Employees.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("date");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("date");

                    b.Property<string>("ModifiedUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("WorkEnd")
                        .HasColumnType("date");

                    b.Property<DateTime>("WorkStart")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("tblEmployees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDay = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(8343),
                            CityId = 1,
                            CreatedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(8344),
                            Description = "Aciklama1",
                            ModifiedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(8345),
                            ModifiedUser = "system",
                            Name = "Serdar",
                            Picture = "user1.png",
                            WorkEnd = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(8342),
                            WorkStart = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(8341)
                        },
                        new
                        {
                            Id = 2,
                            BirthDay = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(8347),
                            CityId = 1,
                            CreatedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(8348),
                            Description = "Aciklama2",
                            ModifiedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(8349),
                            ModifiedUser = "system",
                            Name = "Recep",
                            Picture = "user2.png",
                            WorkEnd = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(8347),
                            WorkStart = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(8346)
                        },
                        new
                        {
                            Id = 3,
                            BirthDay = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(8351),
                            CityId = 1,
                            CreatedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(8352),
                            Description = "Aciklama3",
                            ModifiedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(8352),
                            ModifiedUser = "system",
                            Name = "Melek",
                            Picture = "user3.png",
                            WorkEnd = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(8351),
                            WorkStart = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(8350)
                        });
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Employees.EmployeeDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Fax")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gsm")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("tblEmployeeDetails", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Email = "111@gmail.com",
                            EmployeeId = 1,
                            Fax = "234",
                            Gsm = "1234",
                            Phone = "1234"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            Email = "222@gmail.com",
                            EmployeeId = 2,
                            Fax = "234",
                            Gsm = "1234",
                            Phone = "1234"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 3,
                            Email = "333@gmail.com",
                            EmployeeId = 3,
                            Fax = "234",
                            Gsm = "1234",
                            Phone = "1234"
                        });
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Hospitals.Hospital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("date");

                    b.Property<string>("HospitalName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("HospitalTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("date");

                    b.Property<string>("ModifiedUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("HospitalTypeId");

                    b.ToTable("tblHospitals", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(7553),
                            HospitalName = "AciBadem",
                            HospitalTypeId = 1,
                            ModifiedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(7538),
                            ModifiedUser = "system"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(7555),
                            HospitalName = "Florence Nightingale",
                            HospitalTypeId = 1,
                            ModifiedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(7555),
                            ModifiedUser = "system"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(7557),
                            HospitalName = "Medicana",
                            HospitalTypeId = 1,
                            ModifiedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(7557),
                            ModifiedUser = "system"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(7559),
                            HospitalName = "Beylikduzu Devlet",
                            HospitalTypeId = 2,
                            ModifiedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(7558),
                            ModifiedUser = "system"
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(7560),
                            HospitalName = "KANUNİ SULTAN SÜLEYMAN",
                            HospitalTypeId = 9,
                            ModifiedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(7560),
                            ModifiedUser = "system"
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(7562),
                            HospitalName = "Cam ve Sakura",
                            HospitalTypeId = 3,
                            ModifiedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(7561),
                            ModifiedUser = "system"
                        },
                        new
                        {
                            Id = 7,
                            CreatedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(7564),
                            HospitalName = "Kocaeli Üniversitesi Hastanesi",
                            HospitalTypeId = 4,
                            ModifiedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(7563),
                            ModifiedUser = "system"
                        },
                        new
                        {
                            Id = 8,
                            CreatedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(7565),
                            HospitalName = "Gata",
                            HospitalTypeId = 6,
                            ModifiedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(7565),
                            ModifiedUser = "system"
                        },
                        new
                        {
                            Id = 9,
                            CreatedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(7567),
                            HospitalName = "Bezmialem Vakıf Üni. Tıp Fakültesi Hastanesi",
                            HospitalTypeId = 7,
                            ModifiedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(7566),
                            ModifiedUser = "system"
                        });
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Hospitals.HospitalBranch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("date");

                    b.Property<int>("HospitalId")
                        .HasColumnType("int");

                    b.Property<string>("InvoiceTitle")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("date");

                    b.Property<string>("ModifiedUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("HospitalId");

                    b.ToTable("tblHospitalBranches", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Acibadem/Kadikoy",
                            CityId = 1,
                            CreatedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(7723),
                            HospitalId = 1,
                            InvoiceTitle = "Acibadem Saglik Hizmetleri A.S.",
                            ModifiedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(7724),
                            ModifiedUser = "system",
                            Name = "Merkez"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Çankaya/Ankara",
                            CityId = 1,
                            CreatedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(7726),
                            HospitalId = 1,
                            InvoiceTitle = "Acibadem Saglik Hizmetleri A.S.",
                            ModifiedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(7727),
                            ModifiedUser = "system",
                            Name = "Ankara"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Tepebaşı/Eskişehir",
                            CityId = 1,
                            CreatedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(7729),
                            HospitalId = 1,
                            InvoiceTitle = "Acibadem Saglik Hizmetleri A.S.",
                            ModifiedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(7729),
                            ModifiedUser = "system",
                            Name = "Eskisehir"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Şişli/İstanbul",
                            CityId = 1,
                            CreatedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(7730),
                            HospitalId = 2,
                            InvoiceTitle = "Florence Nightingale Saglik Hizmetleri A.S.",
                            ModifiedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(7731),
                            ModifiedUser = "system",
                            Name = "Merkez"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Beylikdüzü/İstanbul",
                            CityId = 1,
                            CreatedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(7732),
                            HospitalId = 3,
                            InvoiceTitle = "Medikana Saglik Hizmetleri A.S.",
                            ModifiedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(7733),
                            ModifiedUser = "system",
                            Name = "Merkez"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Beylikdüzü/İstanbul",
                            CityId = 1,
                            CreatedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(7734),
                            HospitalId = 4,
                            InvoiceTitle = "Devlet Saglik Hizmetleri A.S.",
                            ModifiedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(7735),
                            ModifiedUser = "system",
                            Name = "Merkez"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Gazi Osman Pasa/İstanbul",
                            CityId = 1,
                            CreatedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(7786),
                            HospitalId = 5,
                            InvoiceTitle = "Devlet Saglik Hizmetleri A.S.",
                            ModifiedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(7787),
                            ModifiedUser = "system",
                            Name = "Merkez"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Basaksehir/İstanbul",
                            CityId = 1,
                            CreatedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(7788),
                            HospitalId = 6,
                            InvoiceTitle = "Devlet Saglik Hizmetleri A.S.",
                            ModifiedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(7789),
                            ModifiedUser = "system",
                            Name = "Merkez"
                        });
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Hospitals.HospitalDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Fax")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gsm")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("HospitalBranchId")
                        .HasColumnType("int");

                    b.Property<string>("Officer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("HospitalBranchId");

                    b.ToTable("tblHospitalDetails", (string)null);
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Hospitals.HospitalType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("tblHospitalTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ozel"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Devlet"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sehir"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Universite"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Vakif"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Askeri"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Sb"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Klinik"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Arastirma"
                        });
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Stocks.Products.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BranchNoId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("date");

                    b.Property<string>("ModifiedUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SutCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SutDescription")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("SutPrice")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("tblProducts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BranchNoId = 1,
                            CompanyId = 1,
                            CreatedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(8502),
                            Description = "Suture Passer, Transosseous",
                            EntryDate = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(8498),
                            ModifiedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(8503),
                            ModifiedUser = "system",
                            Picture = "product1.jpg",
                            ProductCode = "AR-1000",
                            SutCode = "AE-1000",
                            SutDescription = "DÜZ TİTANYUM",
                            SutPrice = 125.75m
                        },
                        new
                        {
                            Id = 2,
                            BranchNoId = 2,
                            CompanyId = 1,
                            CreatedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(8506),
                            Description = "Suture Passer, Transosseous1",
                            EntryDate = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(8504),
                            ModifiedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(8507),
                            ModifiedUser = "system",
                            Picture = "product2.jpg",
                            ProductCode = "AR-1001",
                            SutCode = "AE-1001",
                            SutDescription = "DÜZ TİTANYUM",
                            SutPrice = 155.75m
                        },
                        new
                        {
                            Id = 3,
                            BranchNoId = 1,
                            CompanyId = 1,
                            CreatedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(8509),
                            Description = "Suture Passer, Transosseous2",
                            EntryDate = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(8508),
                            ModifiedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(8509),
                            ModifiedUser = "system",
                            Picture = "product3.jpg",
                            ProductCode = "AR-1002",
                            SutCode = "AE-1002",
                            SutDescription = "DÜZ TİTANYUM",
                            SutPrice = 115.75m
                        },
                        new
                        {
                            Id = 4,
                            BranchNoId = 1,
                            CompanyId = 1,
                            CreatedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(8512),
                            Description = "Suture Passer, Transosseous3",
                            EntryDate = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(8511),
                            ModifiedOn = new DateTime(2022, 1, 18, 16, 11, 56, 357, DateTimeKind.Local).AddTicks(8512),
                            ModifiedUser = "system",
                            Picture = "product4.jpg",
                            ProductCode = "AR-1003",
                            SutCode = "AE-1003",
                            SutDescription = "DÜZ TİTANYUM",
                            SutPrice = 215.25m
                        });
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Stocks.Products.ProductEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("date");

                    b.Property<int>("EntryTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("date");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LotSerial")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("date");

                    b.Property<string>("ModifiedUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("date");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ProductId");

                    b.ToTable("tblProductEntries", (string)null);
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Stocks.Products.StockState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BranchQuantity")
                        .HasColumnType("int");

                    b.Property<int>("ConsigneeQuantity")
                        .HasColumnType("int");

                    b.Property<string>("LotSerial")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ShelfQuantity")
                        .HasColumnType("int");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<int>("TransferedProductQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tblStockStates", (string)null);
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Companies.Company", b =>
                {
                    b.HasOne("SlnErp102.Core.Models.Infos.Companies.CompanyType", "CompanyType")
                        .WithMany("Companies")
                        .HasForeignKey("CompanyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyType");
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Companies.CompanyBranch", b =>
                {
                    b.HasOne("SlnErp102.Core.Models.City", "City")
                        .WithMany("CompanyBranches")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SlnErp102.Core.Models.Infos.Companies.Company", "Company")
                        .WithMany("CompanyBranches")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Companies.CompanyDetail", b =>
                {
                    b.HasOne("SlnErp102.Core.Models.Infos.Companies.Company", "Company")
                        .WithMany("CompanyDetails")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SlnErp102.Core.Models.Department", "Department")
                        .WithMany("CompanyDetails")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Doctors.Doctor", b =>
                {
                    b.HasOne("SlnErp102.Core.Models.City", "City")
                        .WithMany("Doctors")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Doctors.DoctorDetail", b =>
                {
                    b.HasOne("SlnErp102.Core.Models.Infos.Doctors.Doctor", "Doctor")
                        .WithMany("DoctorDetails")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SlnErp102.Core.Models.Infos.Hospitals.Hospital", "Hospital")
                        .WithMany("DoctorDetails")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Employees.Employee", b =>
                {
                    b.HasOne("SlnErp102.Core.Models.City", "City")
                        .WithMany("Employees")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Employees.EmployeeDetail", b =>
                {
                    b.HasOne("SlnErp102.Core.Models.Department", "Department")
                        .WithMany("EmployeeDetails")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SlnErp102.Core.Models.Infos.Employees.Employee", "Employee")
                        .WithMany("EmployeeDetails")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Hospitals.Hospital", b =>
                {
                    b.HasOne("SlnErp102.Core.Models.Infos.Hospitals.HospitalType", "HospitalType")
                        .WithMany("Hospitals")
                        .HasForeignKey("HospitalTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HospitalType");
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Hospitals.HospitalBranch", b =>
                {
                    b.HasOne("SlnErp102.Core.Models.City", "City")
                        .WithMany("HospitalBranches")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SlnErp102.Core.Models.Infos.Hospitals.Hospital", "Hospital")
                        .WithMany("HospitalBranch")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Hospitals.HospitalDetail", b =>
                {
                    b.HasOne("SlnErp102.Core.Models.Department", "Department")
                        .WithMany("HospitalDetails")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SlnErp102.Core.Models.Infos.Hospitals.HospitalBranch", "HospitalBranches")
                        .WithMany("HospitalDetails")
                        .HasForeignKey("HospitalBranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("HospitalBranches");
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Stocks.Products.Product", b =>
                {
                    b.HasOne("SlnErp102.Core.Models.Infos.Companies.Company", "Company")
                        .WithMany("Products")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Stocks.Products.ProductEntry", b =>
                {
                    b.HasOne("SlnErp102.Core.Models.Infos.Companies.Company", null)
                        .WithMany("ProductEntries")
                        .HasForeignKey("CompanyId");

                    b.HasOne("SlnErp102.Core.Models.Stocks.Products.Product", "Product")
                        .WithMany("ProductEntries")
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SlnErp102.Core.Models.City", b =>
                {
                    b.Navigation("CompanyBranches");

                    b.Navigation("Doctors");

                    b.Navigation("Employees");

                    b.Navigation("HospitalBranches");
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Department", b =>
                {
                    b.Navigation("CompanyDetails");

                    b.Navigation("EmployeeDetails");

                    b.Navigation("HospitalDetails");
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Companies.Company", b =>
                {
                    b.Navigation("CompanyBranches");

                    b.Navigation("CompanyDetails");

                    b.Navigation("ProductEntries");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Companies.CompanyType", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Doctors.Doctor", b =>
                {
                    b.Navigation("DoctorDetails");
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Employees.Employee", b =>
                {
                    b.Navigation("EmployeeDetails");
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Hospitals.Hospital", b =>
                {
                    b.Navigation("DoctorDetails");

                    b.Navigation("HospitalBranch");
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Hospitals.HospitalBranch", b =>
                {
                    b.Navigation("HospitalDetails");
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Infos.Hospitals.HospitalType", b =>
                {
                    b.Navigation("Hospitals");
                });

            modelBuilder.Entity("SlnErp102.Core.Models.Stocks.Products.Product", b =>
                {
                    b.Navigation("ProductEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
